import type { App } from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowUpRightFromSquare,
  faAt,
  faBan,
  faCertificate,
  faCheck,
  faChessRook,
  faEdit,
  faGear,
  faGenderless,
  faHourglassHalf,
  faKey,
  faLanguage,
  faMars,
  faPhone,
  faPlus,
  faRobot,
  faRotate,
  faSave,
  faStar,
  faTimes,
  faTrash,
  faUser,
  faUserCheck,
  faUserClock,
  faUsers,
  faUsersGear,
  faVenus,
  faVial,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowUpRightFromSquare,
  faAt,
  faBan,
  faCertificate,
  faCheck,
  faChessRook,
  faEdit,
  faGear,
  faGenderless,
  faHourglassHalf,
  faKey,
  faLanguage,
  faMars,
  faPhone,
  faPlus,
  faRobot,
  faRotate,
  faSave,
  faStar,
  faTimes,
  faTrash,
  faUser,
  faUserCheck,
  faUserClock,
  faUsers,
  faUsersGear,
  faVenus,
  faVial,
);

export default function (app: App) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
