name: Publish Docker Image to Docker Hub
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build Krakenar Frontend
        run: |
          cd ./frontend
          npm clean-install
          npm run build
          cd ../

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract Metadata (Tags, Labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: logitar/krakenar

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          file: backend/src/Krakenar/Dockerfile
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
